# .github/workflows/scheduled-mail-sender.yml

name: Scheduled Supabase Edge Function Caller

# Workflow'un ne zaman çalışacağını tanımlar
on:
  # Her 5 dakikada bir çalışacak Cron zamanlaması (UTC saatiyle)
  schedule:
    - cron: '*/5 * * * *'
  
  # Manuel çalıştırma yeteneği ekler
  workflow_dispatch:

jobs:
  call_edge_function:
    runs-on: ubuntu-latest
    
    steps:
      - name: Log Starting Time
        run: echo "Starting call to Edge Function at $(date)"

      - name: Call Supabase Edge Function with Secret
        run: |
          # URL'yi ve Authorization başlığını Secret'lardan alır
          FUNCTION_URL="${{ secrets.SUPABASE_EDGE_FUNCTION_URL }}"
          AUTH_HEADER="Bearer ${{ secrets.SUPABASE_FUNCTION_SECRET }}"
          
          echo "Calling function: smart-task at ${FUNCTION_URL}" # <-- Fonksiyon adı burada güncellendi
          
          # Edge Function'ı çağırır ve yanıtı kaydeder
          # -f bayrağı sayesinde, 4xx/5xx hata kodları gelirse adım başarısız olur
          response=$(curl -sS -f \
            -X POST "${FUNCTION_URL}" \
            -H "Content-Type: application/json" \
            -H "Authorization: ${AUTH_HEADER}" \
            -d '{}')

          # Yanıtı log'a yazdır
          echo "Edge Function Response: ${response}"

        # env: ortam değişkenleri bu adıma Secret'ları enjekte eder
        env:
          SUPABASE_EDGE_FUNCTION_URL: ${{ secrets.SUPABASE_EDGE_FUNCTION_URL }}
          SUPABASE_FUNCTION_SECRET: ${{ secrets.SUPABASE_FUNCTION_SECRET }}
          
      - name: Log Ending Time
        run: echo "Finished call to Edge Function at $(date)"
